TRAIN:
  LEARNING_RATE: 0.01
  MOMENTUM: 0.9
  BATCH_SIZE: 32
  #orginal 16
  MAX_EPOCH: 50
  SCHEDULER: 'step' # 'step'
  IS_PRETRAINED: false
  PRETRAINED_MODEL_PATH: 'checkpoints/MC4_/models/model.t7'
  OUTPUT_DIR: 'log/'
  DROPOUT_RATE: 0.5
  CONSISTENCY_LOSS: false
  CONSISTENCY_WEIGHTS:
    - 0.05
    - 0.05
    - 0.05
    - 0.05
  LOSS_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0


DEVICES:
  GPU_ID: 
    - 0
  SEED: 1

